import ast
import os
from PIL import Image
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from vlm_research_kit.utils.file_utils import load_yaml
from vlm_research_kit.utils.print_utils import print_bold, print_yellow


def plot_report_generation_metrics(results_path: str):
    """
    Loads and visualizes metrics from a report generation evaluation run.

    This function expects a YAML file containing specific metrics typically
    generated by report generation evaluation scripts, including:
    - Natural Language Generation (NLG) metrics:
        - 'BLEU-1', 'BLEU-2', 'BLEU-3', 'BLEU-4'
        - 'ROUGE-L'
        - 'BERTScore_F1', 'BERTScore_P', 'BERTScore_R'
    - Clinical Efficacy / Accuracy metrics (via CheXbert):
        - 'CheXbert_accuracy'
        - 'CheXbert_classification_report': A nested dictionary with
          precision, recall, f1-score, and support for multiple clinical
          findings (e.g., 'Cardiomegaly', 'Edema', ...) and averages
          ('micro avg', 'macro avg', 'weighted avg').

    It generates three plots:
    1. A horizontal bar chart for overall scalar metrics (BLEU, ROUGE-L,
       BERTScore F1, CheXbert Accuracy).
    2. A grouped bar chart showing Precision, Recall, and F1-score for each
       clinical finding class from the CheXbert report.
    3. A grouped bar chart showing Precision, Recall, and F1-score for the
       average metrics (micro, macro, weighted) from the CheXbert report.

    Args:
        results_path: Path to the YAML file containing the evaluation metrics.
    """
    overall_metrics = load_yaml(results_path)

    if overall_metrics is None:
        return

    # --- Set Plot Style ---
    sns.set_theme(style="whitegrid")

    # --- 1. Plot Scalar Metrics ---
    scalar_metrics = {
        'BLEU-1': overall_metrics['BLEU-1'],
        'BLEU-2': overall_metrics['BLEU-2'],
        'BLEU-3': overall_metrics['BLEU-3'],
        'BLEU-4': overall_metrics['BLEU-4'],
        'ROUGE-L': overall_metrics['ROUGE-L'],
        'CheXbert Acc': overall_metrics['CheXbert_accuracy'],
        'CheXbert Micro F1': overall_metrics['CheXbert_classification_report']['micro avg']['f1-score'],
        'CheXbert Macro F1': overall_metrics['CheXbert_classification_report']['macro avg']['f1-score'],
        'CheXbert cosine similarity': overall_metrics['CheXbert_cosine_similarity'],
        'BERTScore F1': overall_metrics['BERTScore_F1'],
        # BERTScore P/R can be negative, handle separately or omit if confusing
        # 'BERTScore P': overall_metrics.get('BERTScore_P', 0),
        # 'BERTScore R': overall_metrics.get('BERTScore_R', 0),
    }

    if scalar_metrics:
        plt.figure(figsize=(10, 5))
        keys = list(scalar_metrics.keys())
        values = list(scalar_metrics.values())

        bars = plt.barh(keys, values, color=sns.color_palette("viridis", len(keys)))
        plt.xlabel("Score")
        plt.title("Overall Scalar Metrics")
        plt.xlim(0, max(values) * 1.1 if values else 1) # Adjust x-limit
        # Add value labels to the bars
        for bar in bars:
            plt.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height()/2.,
                     f'{bar.get_width():.3f}',
                     va='center', ha='left')
        plt.tight_layout()
        plt.show()
    else:
        print("No scalar metrics found to plot.")


    # --- 2. Plot CheXbert Classification Report (Per Class) ---
    chexbert_report = overall_metrics.get('CheXbert_classification_report')

    if chexbert_report:
        # Separate classes from averages
        class_metrics = {
            k: v for k, v in chexbert_report.items()
            if k not in ['micro avg', 'macro avg', 'weighted avg', 'samples avg']
        }
        avg_metrics = {
            k: v for k, v in chexbert_report.items()
            if k in ['micro avg', 'macro avg', 'weighted avg', 'samples avg']
        }

        if class_metrics:
            # Convert class metrics to DataFrame for easier plotting
            # Keep the 'support' column initially
            df_classes = pd.DataFrame(class_metrics).T

            # Define columns to plot
            plot_cols = ['precision', 'recall', 'f1-score']

            # Check if plot columns exist
            missing_plot_cols = [col for col in plot_cols if col not in df_classes.columns]
            if missing_plot_cols:
                print(f"Warning: Missing plot columns: {missing_plot_cols}. Skipping per-class plot.")
                # Optionally, you could plot only available columns:
                # plot_cols = [col for col in plot_cols if col in df_classes.columns]
                # if not plot_cols: return # Exit if no plot columns left
            else:
                # Check if 'support' column exists for labels
                support_available = 'support' in df_classes.columns
                if not support_available:
                    print("Warning: 'support' column not found. Cannot add support counts to x-axis labels.")

                # Plotting grouped bar chart using ONLY the selected plot_cols
                ax = df_classes[plot_cols].plot(kind='bar', figsize=(15, 7), width=0.8,
                                             color=sns.color_palette("muted", len(plot_cols)))

                plt.title("CheXbert Classification Report (Per Class)")
                plt.ylabel("Score")
                # Update x-axis label to indicate support is shown
                plt.xlabel("Class (n = support count)")
                plt.ylim(0, 1) # P, R, F1 are between 0 and 1
                plt.legend(title='Metric')

                # --- Modify x-axis labels to include support ---
                if support_available:
                    new_labels = []
                    # Iterate through the DataFrame index (class names)
                    for class_name in df_classes.index:
                        support_val = df_classes.loc[class_name, 'support']
                        # Format support as integer, handle potential NaN/None
                        support_str = f"n={int(support_val)}" if pd.notna(support_val) else "n=?"
                        # Combine class name and support count (using newline for potentially better spacing)
                        new_labels.append(f"{class_name}\n({support_str})")

                    # Set the new labels, maintaining rotation and alignment
                    ax.set_xticklabels(new_labels, rotation=45, ha='right')
                else:
                    # If support wasn't available, just apply rotation to original labels
                    plt.xticks(rotation=45, ha='right')
                # --- End of label modification ---

                # Add value labels to the bars
                for container in ax.containers:
                    # Adjust label padding if needed, especially with rotated x-labels
                    ax.bar_label(container, fmt='%.3f', padding=2)

                plt.tight_layout() # Adjust layout AFTER setting new labels and bar labels
                plt.show()
        else:
            print("No per-class CheXbert metrics found to plot.")

        # --- 3. Plot CheXbert Average Metrics ---
        if avg_metrics:
            df_avg = pd.DataFrame(avg_metrics).T
            df_avg = df_avg[['precision', 'recall', 'f1-score']]

            ax_avg = df_avg.plot(kind='bar', figsize=(10, 5), width=0.8,
                                 color=sns.color_palette("muted", 3))

            plt.title("CheXbert Classification Report (Average Metrics)")
            plt.ylabel("Score")
            plt.xlabel("Averaging Method")
            plt.xticks(rotation=0)
            plt.ylim(0, max(df_avg.max()) * 1.1 if not df_avg.empty else 1) # Adjust ylim based on data
            plt.legend(title='Metric')

            # Add value labels
            for container in ax_avg.containers:
                ax_avg.bar_label(container, fmt='%.3f')

            plt.tight_layout()
            plt.show()
        else:
            print("No average CheXbert metrics found to plot.")

    else:
        print("CheXbert classification report not found in the results.")


def display_report_generation_sample(df: pd.DataFrame, index: int):
    """
    Displays a single sample (row) from a report generation evaluation DataFrame.

    This function is primarily designed for use within IPython environments
    (like Jupyter Notebooks or JupyterLab) as it uses IPython.display
    to render images inline. If run outside IPython, it will print text
    outputs and warnings, but cannot display images directly.

    It expects the DataFrame `df` to contain specific columns for the given `index`:
    - 'image_paths': A string containing one or more image file paths,
                     separated by commas.
    - 'prediction': The generated report text (model output).
    - 'reference': The ground truth report text.
    - CheXbert label columns: For each short name in CHEXBERT_SHORT_CLASS_NAMES
      (e.g., 'Cardiomegaly'), it expects columns named like
      'CheXbert_Cardiomegaly_pred' and 'CheXbert_Cardiomegaly_gt',
      containing binary values (0 or 1).
    - Metric columns: Individual sample metrics like 'CheXbert_accuracy',
        'CheXbert_cosine_similarity', 'BERTScore_F1', 'BERTScore_P',
        'BERTScore_R', 'BLEU-1', 'BLEU-2', 'BLEU-3', 'BLEU-4', 'ROUGE-L'.

    Args:
        df: The Pandas DataFrame containing evaluation results per sample.
        index: The integer index of the row (sample) to display from the DataFrame.
    """

    from vlm_research_kit.metrics.biomedical.chexbert import (
        CHEXBERT_CLASS_NAMES,
        CHEXBERT_SHORT_CLASS_NAMES,
    )

    row = df.iloc[index]
    prediction = row.prediction
    reference = row.reference

    print_bold(f"--- Displaying Sample at Index: {index} ---")

    # --- Image Display ---
    try:
        if row.image_paths[0] == '[': # A list of paths
            image_paths = ast.literal_eval(row.image_paths)
        else: # A single path
            image_paths = [row.image_paths]
    except AttributeError: # try "image_path" as a fallback
        image_paths = [row.image_path]
    n_images = len(image_paths)
    
    # Adjust these values to control the default display size
    target_img_width_inches = 5
    target_img_height_inches = 5
    # Calculate total figure size
    total_fig_width = n_images * target_img_width_inches
    total_fig_height = target_img_height_inches

    # Create subplots - squeeze=False ensures axes is always an array, even for 1 image
    fig, axes = plt.subplots(1, n_images,
                                figsize=(total_fig_width, total_fig_height),
                                squeeze=False)
    axes = axes.ravel() # Flatten the axes array for easy iteration

    print_bold("\nImages:")

    for i, path in enumerate(image_paths):
        ax = axes[i]
        try:
            # Load image using Pillow
            img = Image.open(path)
            # Display image using Matplotlib
            ax.imshow(img, cmap='gray' if img.mode != 'RGB' else None) # Use grayscale cmap if not RGB
            ax.set_title(os.path.basename(path), fontsize=10) # Add filename as title
            ax.axis('off') # Hide axis ticks and labels for cleaner look
        except FileNotFoundError:
            print(f"Error: Image file not found at '{path}'")
            ax.text(0.5, 0.5, 'Image not found', ha='center', va='center', color='red', fontsize=9)
            ax.set_title(os.path.basename(path), fontsize=10)
            ax.axis('off')
        except Exception as e:
            print(f"Error loading image '{path}': {e}")
            ax.text(0.5, 0.5, f'Error loading image:\n{e}', ha='center', va='center', color='red', fontsize=9)
            ax.set_title(os.path.basename(path), fontsize=10)
            ax.axis('off')

    plt.tight_layout() # Adjust subplot params for a tight layout
    plt.show() # Display the plot window
    print("-" * 30)
    
    # --- Prediction Text and Labels ---
    print_bold("Prediction Text:")
    print(prediction)
    
    print_bold("\nPrediction's CheXbert Labels:")
    pred_labels = []
    for name, short in zip(CHEXBERT_CLASS_NAMES, CHEXBERT_SHORT_CLASS_NAMES):
        if row[f'CheXbert_{short}_pred'] == 1:
            pred_labels.append(name)
    print(pred_labels)
    print("-" * 30)

    # --- Reference Text and Labels ---
    print_bold("Reference Text:")
    print(reference)

    print_bold("\nReference's CheXbert Labels:")
    gt_labels = []
    for name, short in zip(CHEXBERT_CLASS_NAMES, CHEXBERT_SHORT_CLASS_NAMES):
        if row[f'CheXbert_{short}_gt'] == 1:
            gt_labels.append(name)
    print(gt_labels)
    print("-" * 30)

    # --- Individual Metrics ---
    print_bold("Individual Metrics for this Sample:")
    metric_names = [
        "CheXbert_accuracy",
        "CheXbert_cosine_similarity",
        "BERTScore_F1",
        "BERTScore_P",
        "BERTScore_R",
        "BLEU-1",
        "BLEU-2",
        "BLEU-3",
        "BLEU-4",
        "ROUGE-L",
    ]
    for metric_name in metric_names:
        if metric_name in row:
            print_bold(metric_name, end=' '); print(row[metric_name])
        else:
            print_yellow(f"WARNING: {metric_name} not found in the DataFrame.", bold=True)